// <auto-generated />
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using ProyectoAcortadorURL.Data;

#nullable disable

namespace ProyectoAcortadorURL.Migrations
{
    [DbContext(typeof(UrlShortenerContext))]
    [Migration("20231108233907_AuthMigration")]
    partial class AuthMigration
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "7.0.13");

            modelBuilder.Entity("ProyectoAcortadorURL.Entities.ShortenedURL", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("LongURL")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("ShortURL")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<int>("category")
                        .HasColumnType("INTEGER");

                    b.Property<int>("views")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.ToTable("ShortenedUrls", (string)null);
                });

            modelBuilder.Entity("ProyectoAcortadorURL.Entities.User", b =>
                {
                    b.Property<int>("UserId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Password")
                        .HasColumnType("TEXT");

                    b.Property<string>("Username")
                        .HasColumnType("TEXT");

                    b.HasKey("UserId");

                    b.ToTable("Users", (string)null);

                    b.HasData(
                        new
                        {
                            UserId = 1,
                            Password = "password",
                            Username = "augusto"
                        });
                });
#pragma warning restore 612, 618
        }
    }
}
